# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_auto_20171010_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='recommenders',
            field=models.ManyToManyField(blank=True, related_name='recommend_membership_set', to='model.Idol'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='idol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='model.Idol'),
        ),
    ]
